import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'], weight: ["900"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      
      <body className={notoSansJP.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
